/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GridItemImage = {
  asset?: SanityImageAssetReference;
  media?: unknown // Unable to locate the referenced type "media" in schema
;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoMain?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoBimi?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  contactEmail?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PriceWidget = {
  _type: "priceWidget";
  title?: string;
  price?: number;
  merchant?: "Amazon" | "Noon" | "General";
  affiliateLink?: string;
  badge?: string;
};

export type TopTenListReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topTenList";
};

export type HowToReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "howTo";
};

export type NavigationGrid = {
  _type: "navigationGrid";
  title?: string;
  items?: Array<{
    label?: string;
    description?: string;
    image?: GridItemImage;
    targetPost?: TopTenListReference | HowToReference;
    _type: "gridItem";
    _key: string;
  }>;
};

export type Separator = {
  _type: "separator";
  style?: "line" | "gap";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  schemaType?: "Article" | "NewsArticle" | "HowTo" | "ItemList" | "Product" | "SoftwareApplication";
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type HolidayReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "holiday";
};

export type RelatedLink = {
  _type: "relatedLink";
  label?: string;
  preText?: string;
  targetPost?: TopTenListReference | HowToReference | ToolReference | HolidayReference;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Holiday = {
  _id: string;
  _type: "holiday";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  showAffiliateDisclosure?: boolean;
  description?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  status?: "scheduled" | "cancelled" | "postponed" | "rescheduled";
  startDate?: string;
  endDate?: string;
  isAllDay?: boolean;
  locationName?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    country?: string;
  };
  ticketUrl?: string;
  ticketPrice?: number;
  isTicketAvailable?: boolean;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "green" | "blue" | "amber" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Deal = {
  _id: string;
  _type: "deal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  affiliateLink?: string;
  tags?: Array<string>;
  dealPrice?: number;
  originalPrice?: number;
  discountPercentage?: number;
  couponCode?: string;
  couponNote?: string;
  category?: "Electronics" | "Home & Kitchen" | "Fashion" | "Beauty & Personal Care" | "Toys & Games" | "Books" | "Sports & Outdoors" | "Automotive" | "Health & Wellness" | "Groceries" | "Other";
  dealEndDate?: string;
  isPrimeExclusive?: boolean;
  featured?: boolean;
  isActive?: boolean;
  rating?: number;
  reviewCount?: number;
  seo?: Seo;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  overview?: string;
  heroBadge?: string;
  heroTitleSuffix?: string;
  intro?: string;
  heroTags?: Array<string>;
  componentId?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "blue" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator | {
    _key: string;
  } & RelatedLink>;
  relatedTools?: Array<{
    _key: string;
  } & ToolReference>;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    openGraphImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type InstitutionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "institution";
};

export type AviationEntityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aviationEntity";
};

export type TopTenList = {
  _id: string;
  _type: "topTenList";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  showAffiliateDisclosure?: boolean;
  author?: AuthorReference;
  publishedAt?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  isFeaturedReview?: boolean;
  reviewSection?: "tech" | "home-kitchen" | "beauty" | "parenting" | "health" | "fashion" | "travel" | "automotive" | "food" | "lifestyle";
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  intro?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "green" | "blue" | "amber" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & Table | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Code>;
  listItems?: Array<{
    product?: ProductReference | InstitutionReference | AviationEntityReference;
    badgeLabel?: string;
    rank?: number;
    whySelected?: string;
    _type: "item";
    _key: string;
  }>;
  closingContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  seo?: Seo;
};

export type AviationEntity = {
  _id: string;
  _type: "aviationEntity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  entityType?: "airline" | "airport";
  title?: string;
  slug?: Slug;
  code?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  country?: string;
  website?: string;
  rating?: number;
};

export type Institution = {
  _id: string;
  _type: "institution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: string;
  address?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  curriculum?: "British" | "American" | "IB" | "Indian (CBSE)" | "Indian (ICSE)" | "French" | "Dual (Indian / IB)" | "Dual (British / IB)";
  rating?: "Outstanding" | "Very Good" | "Good" | "Acceptable";
  feeRange?: string;
  website?: string;
  verdict?: string;
  realityCheck?: Array<string>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  brand?: string;
  reviewSection?: "tech" | "home-kitchen" | "beauty" | "parenting" | "health" | "fashion" | "travel" | "automotive" | "food" | "lifestyle";
  displayCategories?: Array<{
    _key: string;
  } & CategoryReference>;
  subCategory?: CategoryReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  affiliateLink?: string;
  retailer?: "Amazon.ae" | "Noon" | "Sharaf DG" | "Official Site";
  price?: number;
  currency?: "AED" | "USD" | "SAR" | "EUR";
  availability?: "https://schema.org/InStock" | "https://schema.org/OutOfStock" | "https://schema.org/PreOrder" | "https://schema.org/LimitedAvailability";
  priceTier?: "Budget" | "Mid-Range" | "Premium";
  customerRating?: number;
  reviewCount?: number;
  ratingSource?: "Amazon.ae" | "Noon" | "Google Shopping" | "Trustpilot";
  realComplaint?: string;
  verdict?: string;
  specifications?: Array<{
    specLabel?: string;
    specValue?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  pros?: Array<string>;
  cons?: Array<string>;
  itemDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & PriceWidget>;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuLabel?: string;
  title?: string;
  slug?: Slug;
  metaTitle?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredPosts?: Array<HolidayReference | TopTenListReference | HowToReference | ToolReference>;
  yearFilters?: Array<number>;
  tags?: Array<string>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  parentCategory?: CategoryReference;
  order?: number;
  isHidden?: boolean;
};

export type HowTo = {
  _id: string;
  _type: "howTo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  Author?: AuthorReference;
  publishedAt?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  intro?: string;
  howToSteps?: Array<{
    title?: string;
    instruction?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & Table | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  schemaType?: "NewsArticle" | "HowTo" | "FAQPage";
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  socialLinks?: Array<string>;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type Table = {
  _type: "table";
  rows?: Array<{
    _key: string;
  } & TableRow>;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | GridItemImage | SiteSettings | SanityImageCrop | SanityImageHotspot | PriceWidget | TopTenListReference | HowToReference | NavigationGrid | Separator | Seo | ToolReference | HolidayReference | RelatedLink | CategoryReference | Holiday | Slug | ProductReference | Deal | Tool | AuthorReference | InstitutionReference | AviationEntityReference | TopTenList | AviationEntity | Institution | Product | Category | HowTo | Author | Code | Table | TableRow | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
