/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GridItemImage = {
  asset?: SanityImageAssetReference;
  media?: unknown // Unable to locate the referenced type "media" in schema
;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoMain?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoBimi?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  contactEmail?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PriceWidget = {
  _type: "priceWidget";
  title?: string;
  price?: number;
  merchant?: "Amazon" | "Noon" | "General";
  affiliateLink?: string;
  badge?: string;
};

export type TopTenListReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topTenList";
};

export type HowToReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "howTo";
};

export type NavigationGrid = {
  _type: "navigationGrid";
  title?: string;
  items?: Array<{
    label?: string;
    description?: string;
    image?: GridItemImage;
    targetPost?: TopTenListReference | HowToReference;
    _type: "gridItem";
    _key: string;
  }>;
};

export type Separator = {
  _type: "separator";
  style?: "line" | "gap";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  schemaType?: "Article" | "NewsArticle" | "HowTo" | "ItemList" | "Product" | "SoftwareApplication";
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type HolidayReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "holiday";
};

export type RelatedLink = {
  _type: "relatedLink";
  label?: string;
  preText?: string;
  targetPost?: TopTenListReference | HowToReference | ToolReference | HolidayReference;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Holiday = {
  _id: string;
  _type: "holiday";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  showAffiliateDisclosure?: boolean;
  description?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  status?: "scheduled" | "cancelled" | "postponed" | "rescheduled";
  startDate?: string;
  endDate?: string;
  isAllDay?: boolean;
  locationName?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    country?: string;
  };
  ticketUrl?: string;
  ticketPrice?: number;
  isTicketAvailable?: boolean;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "green" | "blue" | "amber" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Deal = {
  _id: string;
  _type: "deal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  affiliateLink?: string;
  tags?: Array<string>;
  dealPrice?: number;
  originalPrice?: number;
  discountPercentage?: number;
  couponCode?: string;
  couponNote?: string;
  category?: "Electronics" | "Home & Kitchen" | "Fashion" | "Beauty & Personal Care" | "Toys & Games" | "Books" | "Sports & Outdoors" | "Automotive" | "Health & Wellness" | "Groceries" | "Other";
  dealEndDate?: string;
  isPrimeExclusive?: boolean;
  featured?: boolean;
  isActive?: boolean;
  rating?: number;
  reviewCount?: number;
  seo?: Seo;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  overview?: string;
  heroBadge?: string;
  heroTitleSuffix?: string;
  intro?: string;
  heroTags?: Array<string>;
  componentId?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "blue" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator | {
    _key: string;
  } & RelatedLink>;
  relatedTools?: Array<{
    _key: string;
  } & ToolReference>;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    openGraphImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type InstitutionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "institution";
};

export type AviationEntityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aviationEntity";
};

export type TopTenList = {
  _id: string;
  _type: "topTenList";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  showAffiliateDisclosure?: boolean;
  author?: AuthorReference;
  publishedAt?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  isFeaturedReview?: boolean;
  reviewSection?: "tech" | "home-kitchen" | "beauty" | "parenting" | "health" | "fashion" | "travel" | "automotive" | "food" | "lifestyle";
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  intro?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "green" | "blue" | "amber" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  } | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & Table | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Code>;
  listItems?: Array<{
    product?: ProductReference | InstitutionReference | AviationEntityReference;
    badgeLabel?: string;
    rank?: number;
    whySelected?: string;
    _type: "item";
    _key: string;
  }>;
  closingContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Table | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  seo?: Seo;
};

export type AviationEntity = {
  _id: string;
  _type: "aviationEntity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  entityType?: "airline" | "airport";
  title?: string;
  slug?: Slug;
  code?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  country?: string;
  website?: string;
  rating?: number;
};

export type Institution = {
  _id: string;
  _type: "institution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: string;
  address?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  curriculum?: "British" | "American" | "IB" | "Indian (CBSE)" | "Indian (ICSE)" | "French" | "Dual (Indian / IB)" | "Dual (British / IB)";
  rating?: "Outstanding" | "Very Good" | "Good" | "Acceptable";
  feeRange?: string;
  website?: string;
  verdict?: string;
  realityCheck?: Array<string>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  brand?: string;
  reviewSection?: "tech" | "home-kitchen" | "beauty" | "parenting" | "health" | "fashion" | "travel" | "automotive" | "food" | "lifestyle";
  displayCategories?: Array<{
    _key: string;
  } & CategoryReference>;
  subCategory?: CategoryReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  affiliateLink?: string;
  retailer?: "Amazon.ae" | "Noon" | "Sharaf DG" | "Official Site";
  price?: number;
  currency?: "AED" | "USD" | "SAR" | "EUR";
  availability?: "https://schema.org/InStock" | "https://schema.org/OutOfStock" | "https://schema.org/PreOrder" | "https://schema.org/LimitedAvailability";
  priceTier?: "Budget" | "Mid-Range" | "Premium";
  customerRating?: number;
  reviewCount?: number;
  ratingSource?: "Amazon.ae" | "Noon" | "Google Shopping" | "Trustpilot";
  realComplaint?: string;
  verdict?: string;
  specifications?: Array<{
    specLabel?: string;
    specValue?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  pros?: Array<string>;
  cons?: Array<string>;
  itemDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & PriceWidget>;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuLabel?: string;
  title?: string;
  slug?: Slug;
  metaTitle?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredPosts?: Array<HolidayReference | TopTenListReference | HowToReference | ToolReference>;
  yearFilters?: Array<number>;
  tags?: Array<string>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  parentCategory?: CategoryReference;
  order?: number;
  isHidden?: boolean;
};

export type HowTo = {
  _id: string;
  _type: "howTo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  Author?: AuthorReference;
  publishedAt?: string;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  intro?: string;
  howToSteps?: Array<{
    title?: string;
    instruction?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & Table | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Code | {
    _key: string;
  } & Separator>;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }>;
  schemaType?: "NewsArticle" | "HowTo" | "FAQPage";
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  socialLinks?: Array<string>;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type Table = {
  _type: "table";
  rows?: Array<{
    _key: string;
  } & TableRow>;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | GridItemImage | SiteSettings | SanityImageCrop | SanityImageHotspot | PriceWidget | TopTenListReference | HowToReference | NavigationGrid | Separator | Seo | ToolReference | HolidayReference | RelatedLink | CategoryReference | Holiday | Slug | ProductReference | Deal | Tool | AuthorReference | InstitutionReference | AviationEntityReference | TopTenList | AviationEntity | Institution | Product | Category | HowTo | Author | Code | Table | TableRow | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/[category]/[slug]/page.tsx
// Variable: HOW_TO_QUERY
// Query: *[_type == "howTo" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    publishedAt,    intro,    body,    faqs,     howToSteps,    "author": Author->{ name, image, bio },    mainImage {       alt,      "url": asset->url,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    "categories": categories[]->{ "slug": slug.current, title },    seo { metaTitle, metaDescription, shareImage }  }
export type HOW_TO_QUERYResult = {
  _id: string;
  _type: "howTo";
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  intro: string | null;
  body: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "h5" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  }> | null;
  faqs: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faq";
    _key: string;
  }> | null;
  howToSteps: Array<{
    title?: string;
    instruction?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }> | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
  mainImage: {
    alt: string | null;
    url: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  categories: Array<{
    slug: string | null;
    title: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    shareImage: null;
  } | null;
} | null;

// Source: ./src/app/sitemap.ts
// Variable: query
// Query: *[_type in ["article", "product", "deal", "howTo", "topTenList"] && defined(slug.current)] {      _type,      "slug": slug.current,      _updatedAt,      "category": category->slug.current    }
export type QueryResult = Array<{
  _type: "deal";
  slug: string | null;
  _updatedAt: string;
  category: null;
} | {
  _type: "howTo";
  slug: string | null;
  _updatedAt: string;
  category: null;
} | {
  _type: "product";
  slug: string | null;
  _updatedAt: string;
  category: null;
} | {
  _type: "topTenList";
  slug: string | null;
  _updatedAt: string;
  category: null;
}>;

// Source: ./src/sanity/queries/category.queries.ts
// Variable: ALL_CATEGORIES
// Query: *[_type == "category" && defined(slug.current)] | order(title asc){    _id,    title,    "slug": slug.current,    description,    mainImage { "url": asset->url, alt }  }
export type ALL_CATEGORIESResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  mainImage: null;
}>;
// Variable: CATEGORY_BY_SLUG
// Query: *[_type == "category" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    mainImage { "url": asset->url, alt },    seo { metaTitle, metaDescription }  }
export type CATEGORY_BY_SLUGResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  mainImage: null;
  seo: null;
} | null;
// Variable: CATEGORY_POSTS
// Query: *[_type in ["article", "product", "topTenList", "howTo"]     && references(*[_type == "category" && slug.current == $category]._id)]    | order(publishedAt desc)[0...50]{      _id,      _type,      title,      "slug": slug.current,      mainImage { "url": asset->url, alt },      publishedAt    }
export type CATEGORY_POSTSResult = Array<{
  _id: string;
  _type: "howTo";
  title: string | null;
  slug: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
} | {
  _id: string;
  _type: "product";
  title: string | null;
  slug: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  publishedAt: null;
} | {
  _id: string;
  _type: "topTenList";
  title: string | null;
  slug: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
}>;
// Variable: CATEGORY_PRODUCTS
// Query: *[_type == "product" && category->slug.current == $slug]    | order(publishedAt desc)[0...50]{      _id,      title,      "slug": slug.current,      price,      currency,      mainImage { "url": asset->url, alt },      customerRating,      intro,      reviewCount    }
export type CATEGORY_PRODUCTSResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  currency: "AED" | "EUR" | "SAR" | "USD" | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  customerRating: number | null;
  intro: null;
  reviewCount: number | null;
}>;

// Source: ./src/sanity/queries/deal.queries.ts
// Variable: ALL_ACTIVE_DEALS
// Query: *[_type == "deal" && isActive == true] | order(featured desc, _createdAt desc) {    _type, _id, _createdAt,    "title": coalesce(title, product->title),    description,    "image": coalesce(image.asset->url, product->mainImage.asset->url),    "affiliateLink": coalesce(affiliateLink, product->affiliateLink),    // ✅ CRITICAL ADDITION: Fetch the slug of the related product review    "reviewSlug": product->slug.current,     originalPrice, dealPrice, discountPercentage, category,    dealEndDate, isPrimeExclusive, featured, couponCode, couponNote,    "rating": coalesce(rating, product->customerRating),    "reviewCount": coalesce(reviewCount, product->reviewCount)  }
export type ALL_ACTIVE_DEALSResult = Array<{
  _type: "deal";
  _id: string;
  _createdAt: string;
  title: string | null;
  description: string | null;
  image: string | null;
  affiliateLink: string | null;
  reviewSlug: string | null;
  originalPrice: number | null;
  dealPrice: number | null;
  discountPercentage: number | null;
  category: "Automotive" | "Beauty & Personal Care" | "Books" | "Electronics" | "Fashion" | "Groceries" | "Health & Wellness" | "Home & Kitchen" | "Other" | "Sports & Outdoors" | "Toys & Games" | null;
  dealEndDate: string | null;
  isPrimeExclusive: boolean | null;
  featured: boolean | null;
  couponCode: string | null;
  couponNote: string | null;
  rating: number | null;
  reviewCount: number | null;
}>;
// Variable: FEATURED_DEALS
// Query: *[_type == "deal" && isActive == true && featured == true]     | order(_createdAt desc)[0...10] {      _type, _id, _createdAt,      "title": coalesce(title, product->title),      description,      "image": coalesce(image.asset->url, product->mainImage.asset->url),      "affiliateLink": coalesce(affiliateLink, product->affiliateLink),      "reviewSlug": product->slug.current,      originalPrice, dealPrice, discountPercentage, category,      dealEndDate, isPrimeExclusive, couponCode, couponNote,      "rating": coalesce(rating, product->customerRating),      "reviewCount": coalesce(reviewCount, product->reviewCount)    }
export type FEATURED_DEALSResult = Array<{
  _type: "deal";
  _id: string;
  _createdAt: string;
  title: string | null;
  description: string | null;
  image: string | null;
  affiliateLink: string | null;
  reviewSlug: string | null;
  originalPrice: number | null;
  dealPrice: number | null;
  discountPercentage: number | null;
  category: "Automotive" | "Beauty & Personal Care" | "Books" | "Electronics" | "Fashion" | "Groceries" | "Health & Wellness" | "Home & Kitchen" | "Other" | "Sports & Outdoors" | "Toys & Games" | null;
  dealEndDate: string | null;
  isPrimeExclusive: boolean | null;
  couponCode: string | null;
  couponNote: string | null;
  rating: number | null;
  reviewCount: number | null;
}>;
// Variable: DEALS_BY_CATEGORY
// Query: *[_type == "deal" && isActive == true && category == $category]     | order(_createdAt desc)[0...50] {      _type, _id, _createdAt,      "title": coalesce(title, product->title),      description,      "image": coalesce(image.asset->url, product->mainImage.asset->url),      "affiliateLink": coalesce(affiliateLink, product->affiliateLink),      "reviewSlug": product->slug.current,      originalPrice, dealPrice, discountPercentage,      dealEndDate, isPrimeExclusive, couponCode, couponNote,      "rating": coalesce(rating, product->customerRating),      "reviewCount": coalesce(reviewCount, product->reviewCount)    }
export type DEALS_BY_CATEGORYResult = Array<{
  _type: "deal";
  _id: string;
  _createdAt: string;
  title: string | null;
  description: string | null;
  image: string | null;
  affiliateLink: string | null;
  reviewSlug: string | null;
  originalPrice: number | null;
  dealPrice: number | null;
  discountPercentage: number | null;
  dealEndDate: string | null;
  isPrimeExclusive: boolean | null;
  couponCode: string | null;
  couponNote: string | null;
  rating: number | null;
  reviewCount: number | null;
}>;

// Source: ./src/sanity/queries/global.queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _type,    title,    description,    "logoMain": logoMain.asset->url,    "logoIcon": logoIcon.asset->url,    "logoBimi": logoBimi.asset->url,    "ogImage": ogImage.asset->url,    socialLinks[] { platform, url },    contactEmail  }
export type SITE_SETTINGS_QUERYResult = {
  _type: "siteSettings";
  title: string | null;
  description: string | null;
  logoMain: string | null;
  logoIcon: string | null;
  logoBimi: string | null;
  ogImage: string | null;
  socialLinks: Array<{
    platform: string | null;
    url: string | null;
  }> | null;
  contactEmail: string | null;
} | null;
// Variable: NAVIGATION_MENU
// Query: *[_type == "navigationMenu"][0] {    _id,    title,    items[] {      _key,      title,      url,      children[] {        _key,        title,        url      }    }  }
export type NAVIGATION_MENUResult = null;
// Variable: FOOTER_DATA
// Query: *[_type == "footerSettings"][0] {    _id,    companyInfo,    links[] { title, url },    socialLinks[] { platform, url },    copyrightText  }
export type FOOTER_DATAResult = null;

// Source: ./src/sanity/queries/legacy.queries.ts
// Variable: HOME_QUERY
// Query: {  "heroPost": coalesce(    *[_type in ["topTenList", "article"] && isFeaturedOnHome == true] | order(publishedAt desc) [0],    *[_type in ["topTenList", "article"]] | order(publishedAt desc) [0]  ) {    _id,    title,    "slug": slug.current,    intro,    mainImage,    "categorySlug": coalesce(categories[0]->slug.current, category->slug.current)  },  "sections": *[_type == "category" && slug.current in $categories] | order(order asc, title asc) {    title,    "slug": slug.current,    description,    "posts": *[      (_type in ["topTenList", "article", "tool", "product"]) &&      (        ^._id in categories[]._ref ||        ^._id in displayCategories[]._ref ||        category._ref == ^._id ||        categories[0]._ref == ^._id      )    ] | order(publishedAt desc)[0...4] {      _id,      _type,      title,      "slug": slug.current,      publishedAt,      mainImage    }  },  "upcomingPosts": *[_type in ["topTenList", "article"] && category->slug.current == "upcoming"] | order(publishedAt desc)[0...4] {    _id,    title,    "slug": slug.current,    mainImage  }}
export type HOME_QUERYResult = {
  heroPost: {
    _id: string;
    title: string | null;
    slug: string | null;
    intro: string | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    categorySlug: string | null;
  } | null;
  sections: Array<{
    title: string | null;
    slug: string | null;
    description: string | null;
    posts: Array<{
      _id: string;
      _type: "product";
      title: string | null;
      slug: string | null;
      publishedAt: null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | {
      _id: string;
      _type: "tool";
      title: string | null;
      slug: string | null;
      publishedAt: null;
      mainImage: null;
    } | {
      _id: string;
      _type: "topTenList";
      title: string | null;
      slug: string | null;
      publishedAt: string | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }>;
  }>;
  upcomingPosts: Array<never>;
};
// Variable: CATEGORY_PAGE_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    title,     description,     "slug": slug.current,    "seo": seo { metaTitle, metaDescription },    "mainImage": coalesce(      mainImage,       image,      *[references(^._id)][0].mainImage    ) { "url": asset->url, alt },    "items": *[      _type in ["topTenList", "howTo", "tool", "holiday", "deal", "article"] &&      (references(^._id) || category._ref == ^._id || categories[]._ref == ^._id)    ] | order(publishedAt desc)[0...100] {       _type, title, "slug": slug.current, publishedAt,      "mainImage": coalesce(mainImage, image, product->mainImage) { "url": asset->url, alt },      "rawExcerpt": coalesce(description, "", "")    }  }
export type CATEGORY_PAGE_QUERYResult = {
  title: string | null;
  description: string | null;
  slug: string | null;
  seo: null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  items: Array<{
    _type: "deal";
    title: string | null;
    slug: string | null;
    publishedAt: null;
    mainImage: {
      url: string | null;
      alt: null;
    } | {
      url: string | null;
      alt: string | null;
    } | null;
    rawExcerpt: string | "";
  } | {
    _type: "holiday";
    title: string | null;
    slug: string | null;
    publishedAt: null;
    mainImage: {
      url: string | null;
      alt: string | null;
    } | null;
    rawExcerpt: string | "";
  } | {
    _type: "howTo";
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    mainImage: {
      url: string | null;
      alt: string | null;
    } | null;
    rawExcerpt: "";
  } | {
    _type: "tool";
    title: string | null;
    slug: string | null;
    publishedAt: null;
    mainImage: null;
    rawExcerpt: "";
  } | {
    _type: "topTenList";
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    mainImage: {
      url: string | null;
      alt: string | null;
    } | null;
    rawExcerpt: "";
  }>;
} | null;
// Variable: GENERIC_POST_QUERY
// Query: *[slug.current == $slug][0]{    _type,    "slug": slug.current, _id, title, description,    "seoTitle": coalesce(seo.metaTitle, title),    "seoDescription": "",    "mainImage": coalesce(mainImage, image, coverImage, product->mainImage) { "url": asset->url, alt },    "category": coalesce(categories[0], category)->{ "title": title, "slug": slug.current, "menuLabel": menuLabel },    "publishedAt": _createdAt, "_updatedAt": _updatedAt,    "intro": intro,    "body": body,    "content": content,    "procedure": procedure,    "closingContent": closingContent,    faqs[] { _key, question, answer },    startDate, endDate, locationName, address, ticketPrice  }
export type GENERIC_POST_QUERYResult = {
  _type: "author";
  slug: string | null;
  _id: string;
  title: null;
  description: null;
  seoTitle: null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: null;
  } | null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "aviationEntity";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "category";
  slug: string | null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "deal";
  slug: string | null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: null;
  } | {
    url: string | null;
    alt: string | null;
  } | null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "holiday";
  slug: string | null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
    menuLabel: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  body: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "h5" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "amber" | "blue" | "green" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  }> | null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  startDate: string | null;
  endDate: string | null;
  locationName: string | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    country?: string;
  } | null;
  ticketPrice: number | null;
} | {
  _type: "howTo";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
    menuLabel: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  intro: string | null;
  body: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "h5" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  }> | null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "institution";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: string | null;
  ticketPrice: null;
} | {
  _type: "product";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "sanity.fileAsset";
  slug: null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "sanity.imageAsset";
  slug: null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "siteSettings";
  slug: null;
  _id: string;
  title: string | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: null;
  category: null;
  publishedAt: string;
  _updatedAt: string;
  intro: null;
  body: null;
  content: null;
  procedure: null;
  closingContent: null;
  faqs: null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "tool";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: null;
  category: {
    title: string | null;
    slug: string | null;
    menuLabel: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  intro: string | null;
  body: null;
  content: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "blue" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  }> | null;
  procedure: null;
  closingContent: null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: string | null;
  }> | null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | {
  _type: "topTenList";
  slug: string | null;
  _id: string;
  title: string | null;
  description: null;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
    menuLabel: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  intro: string | null;
  body: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "h5" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "amber" | "blue" | "green" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  }> | null;
  content: null;
  procedure: null;
  closingContent: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  startDate: null;
  endDate: null;
  locationName: null;
  address: null;
  ticketPrice: null;
} | null;
// Variable: REVIEWS_HUB_QUERY
// Query: {  "featured": *[_type == "product" && isFeaturedReview == true] | order(_updatedAt desc) [0...8] {    _id, title, "rating": customerRating, "slug": slug.current,    "imageUrl": coalesce(image.asset->url, mainImage.asset->url)  },  "reviews": *[_type == "product"] | order(_createdAt desc) [0...50] {    _id, title, "rating": customerRating, "slug": slug.current,    "section": reviewSection,    "subCategoryTitle": subCategory->menuLabel,    "imageUrl": coalesce(image.asset->url, mainImage.asset->url)  }}
export type REVIEWS_HUB_QUERYResult = {
  featured: Array<never>;
  reviews: Array<{
    _id: string;
    title: string | null;
    rating: number | null;
    slug: string | null;
    section: "automotive" | "beauty" | "fashion" | "food" | "health" | "home-kitchen" | "lifestyle" | "parenting" | "tech" | "travel" | null;
    subCategoryTitle: string | null;
    imageUrl: string | null;
  }>;
};

// Source: ./src/sanity/queries/product.queries.ts
// Variable: PRODUCT_BY_SLUG
// Query: *[_type == "product" && slug.current == $slug][0] {    _type,    _id,    title,    brand,    "slug": slug.current,    price,    currency,    availability,    priceTier,    retailer,    affiliateLink,    pros,    cons,    keyFeatures,    specifications[] { specLabel, specValue },    customerRating,    reviewCount,    verdict,    mainImage { "url": asset->url, alt },    itemDescription,     // SEO Data    "seoTitle": coalesce(seo.metaTitle, title),    "seoDescription": coalesce(seo.metaDescription, description, intro),    "seoImage": coalesce(seo.openGraphImage.asset->url, mainImage.asset->url),    "category": category->{title, "slug": slug.current}  }
export type PRODUCT_BY_SLUGResult = {
  _type: "product";
  _id: string;
  title: string | null;
  brand: string | null;
  slug: string | null;
  price: number | null;
  currency: "AED" | "EUR" | "SAR" | "USD" | null;
  availability: "https://schema.org/InStock" | "https://schema.org/LimitedAvailability" | "https://schema.org/OutOfStock" | "https://schema.org/PreOrder" | null;
  priceTier: "Budget" | "Mid-Range" | "Premium" | null;
  retailer: "Amazon.ae" | "Noon" | "Official Site" | "Sharaf DG" | null;
  affiliateLink: string | null;
  pros: Array<string> | null;
  cons: Array<string> | null;
  keyFeatures: Array<string> | null;
  specifications: Array<{
    specLabel: string | null;
    specValue: string | null;
  }> | null;
  customerRating: number | null;
  reviewCount: number | null;
  verdict: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  itemDescription: Array<{
    _key: string;
  } & PriceWidget | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: string | null;
  category: null;
} | null;
// Variable: ALL_PRODUCTS
// Query: *[_type == "product"] | order(publishedAt desc)[0...100]{    _id,    title,    "slug": slug.current,    brand,    price,    currency,    mainImage { "url": asset->url, alt },    customerRating,    reviewCount,    "category": category->title,    publishedAt  }
export type ALL_PRODUCTSResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  brand: string | null;
  price: number | null;
  currency: "AED" | "EUR" | "SAR" | "USD" | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  customerRating: number | null;
  reviewCount: number | null;
  category: null;
  publishedAt: null;
}>;
// Variable: PRODUCTS_BY_CATEGORY
// Query: *[_type == "product" && category->slug.current == $categorySlug]     | order(publishedAt desc)[0...50]{      _id,      title,      "slug": slug.current,      brand,      price,      currency,      mainImage { "url": asset->url, alt },      customerRating,      reviewCount,      publishedAt    }
export type PRODUCTS_BY_CATEGORYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  brand: string | null;
  price: number | null;
  currency: "AED" | "EUR" | "SAR" | "USD" | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  customerRating: number | null;
  reviewCount: number | null;
  publishedAt: null;
}>;
// Variable: PRODUCT_SEARCH
// Query: *[_type == "product" && (title match $searchTerm || brand match $searchTerm)]    | order(publishedAt desc)[0...50]{      _id,      title,      "slug": slug.current,      brand,      price,      currency,      mainImage { "url": asset->url, alt },      customerRating,      reviewCount    }
export type PRODUCT_SEARCHResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  brand: string | null;
  price: number | null;
  currency: "AED" | "EUR" | "SAR" | "USD" | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  customerRating: number | null;
  reviewCount: number | null;
}>;

// Source: ./src/sanity/queries/topten.queries.ts
// Variable: TOP_TEN_BY_SLUG
// Query: *[_type == "topTenList" && slug.current == $slug][0] {    _type,    title,    "slug": slug.current,    publishedAt,    "updatedAt": _updatedAt,     "seoTitle": coalesce(seo.metaTitle, title),    "seoDescription": "",    mainImage { "url": asset->url, alt },    intro,    "body": body[],    closingContent,    showAffiliateDisclosure,    faqs[] { _key, question, answer },    listItems[] | order(rank asc) {      _key, rank, badgeLabel, whySelected, customVerdict,      product->{        _type, title,        "slug": slug.current,        priceTier, price, currency, availability,         affiliateLink, customerRating, verdict,        location, curriculum, feeRange, realityCheck, website,        "rating": coalesce(rating, customerRating),        entityType, code, country,        mainImage { "url": asset->url, alt },        heroFeature, keyFeatures[], pros[], cons[],        specifications[] { specLabel, specValue }      }    }  }
export type TOP_TEN_BY_SLUGResult = {
  _type: "topTenList";
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string;
  seoTitle: string | null;
  seoDescription: "";
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  intro: string | null;
  body: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & NavigationGrid | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "h5" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    display?: "full" | "left" | "right";
    _type: "image";
    _key: string;
  } | {
    cards?: Array<{
      title?: string;
      description?: string;
      variant?: "amber" | "blue" | "green" | "purple";
      _key: string;
    }>;
    _type: "infoCards";
    _key: string;
  }> | null;
  closingContent: Array<{
    _key: string;
  } & Code | {
    _key: string;
  } & RelatedLink | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Table | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  showAffiliateDisclosure: boolean | null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  listItems: Array<{
    _key: string;
    rank: number | null;
    badgeLabel: string | null;
    whySelected: string | null;
    customVerdict: null;
    product: {
      _type: "aviationEntity";
      title: string | null;
      slug: string | null;
      priceTier: null;
      price: null;
      currency: null;
      availability: null;
      affiliateLink: null;
      customerRating: null;
      verdict: null;
      location: null;
      curriculum: null;
      feeRange: null;
      realityCheck: null;
      website: string | null;
      rating: number | null;
      entityType: "airline" | "airport" | null;
      code: string | null;
      country: string | null;
      mainImage: {
        url: string | null;
        alt: string | null;
      } | null;
      heroFeature: null;
      keyFeatures: null;
      pros: null;
      cons: null;
      specifications: null;
    } | {
      _type: "institution";
      title: string | null;
      slug: string | null;
      priceTier: null;
      price: null;
      currency: null;
      availability: null;
      affiliateLink: null;
      customerRating: null;
      verdict: string | null;
      location: string | null;
      curriculum: "American" | "British" | "Dual (British / IB)" | "Dual (Indian / IB)" | "French" | "IB" | "Indian (CBSE)" | "Indian (ICSE)" | null;
      feeRange: string | null;
      realityCheck: Array<string> | null;
      website: string | null;
      rating: "Acceptable" | "Good" | "Outstanding" | "Very Good" | null;
      entityType: null;
      code: null;
      country: null;
      mainImage: {
        url: string | null;
        alt: string | null;
      } | null;
      heroFeature: null;
      keyFeatures: null;
      pros: null;
      cons: null;
      specifications: null;
    } | {
      _type: "product";
      title: string | null;
      slug: string | null;
      priceTier: "Budget" | "Mid-Range" | "Premium" | null;
      price: number | null;
      currency: "AED" | "EUR" | "SAR" | "USD" | null;
      availability: "https://schema.org/InStock" | "https://schema.org/LimitedAvailability" | "https://schema.org/OutOfStock" | "https://schema.org/PreOrder" | null;
      affiliateLink: string | null;
      customerRating: number | null;
      verdict: string | null;
      location: null;
      curriculum: null;
      feeRange: null;
      realityCheck: null;
      website: null;
      rating: number | null;
      entityType: null;
      code: null;
      country: null;
      mainImage: {
        url: string | null;
        alt: string | null;
      } | null;
      heroFeature: null;
      keyFeatures: Array<string> | null;
      pros: Array<string> | null;
      cons: Array<string> | null;
      specifications: Array<{
        specLabel: string | null;
        specValue: string | null;
      }> | null;
    } | null;
  }> | null;
} | null;
// Variable: ALL_TOP_TEN_LISTS
// Query: *[_type == "topTenList"] | order(publishedAt desc)[0...100]{    _id,    title,    "slug": slug.current,    publishedAt,    mainImage { "url": asset->url, alt },    intro  }
export type ALL_TOP_TEN_LISTSResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  intro: string | null;
}>;
// Variable: TOP_TEN_LISTS_BY_CATEGORY
// Query: *[_type == "topTenList" && category->slug.current == $categorySlug]    | order(publishedAt desc)[0...50]{      _id,      title,      "slug": slug.current,      publishedAt,      mainImage { "url": asset->url, alt },      intro    }
export type TOP_TEN_LISTS_BY_CATEGORYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  } | null;
  intro: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"howTo\" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    publishedAt,\n    intro,\n    body,\n    faqs, \n    howToSteps,\n    \"author\": Author->{ name, image, bio },\n    mainImage { \n      alt,\n      \"url\": asset->url,\n      \"lqip\": asset->metadata.lqip,\n      \"dimensions\": asset->metadata.dimensions\n    },\n    \"categories\": categories[]->{ \"slug\": slug.current, title },\n    seo { metaTitle, metaDescription, shareImage }\n  }\n": HOW_TO_QUERYResult;
    "*[_type in [\"article\", \"product\", \"deal\", \"howTo\", \"topTenList\"] && defined(slug.current)] {\n      _type,\n      \"slug\": slug.current,\n      _updatedAt,\n      \"category\": category->slug.current\n    }": QueryResult;
    "\n  *[_type == \"category\" && defined(slug.current)] | order(title asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    mainImage { \"url\": asset->url, alt }\n  }\n": ALL_CATEGORIESResult;
    "\n  *[_type == \"category\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    mainImage { \"url\": asset->url, alt },\n    seo { metaTitle, metaDescription }\n  }\n": CATEGORY_BY_SLUGResult;
    "\n  *[_type in [\"article\", \"product\", \"topTenList\", \"howTo\"] \n    && references(*[_type == \"category\" && slug.current == $category]._id)]\n    | order(publishedAt desc)[0...50]{\n      _id,\n      _type,\n      title,\n      \"slug\": slug.current,\n      mainImage { \"url\": asset->url, alt },\n      publishedAt\n    }\n": CATEGORY_POSTSResult;
    "\n  *[_type == \"product\" && category->slug.current == $slug]\n    | order(publishedAt desc)[0...50]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      price,\n      currency,\n      mainImage { \"url\": asset->url, alt },\n      customerRating,\n      intro,\n      reviewCount\n    }\n": CATEGORY_PRODUCTSResult;
    "\n  *[_type == \"deal\" && isActive == true] | order(featured desc, _createdAt desc) {\n    _type, _id, _createdAt,\n    \"title\": coalesce(title, product->title),\n    description,\n    \"image\": coalesce(image.asset->url, product->mainImage.asset->url),\n    \"affiliateLink\": coalesce(affiliateLink, product->affiliateLink),\n    // \u2705 CRITICAL ADDITION: Fetch the slug of the related product review\n    \"reviewSlug\": product->slug.current, \n    originalPrice, dealPrice, discountPercentage, category,\n    dealEndDate, isPrimeExclusive, featured, couponCode, couponNote,\n    \"rating\": coalesce(rating, product->customerRating),\n    \"reviewCount\": coalesce(reviewCount, product->reviewCount)\n  }\n": ALL_ACTIVE_DEALSResult;
    "\n  *[_type == \"deal\" && isActive == true && featured == true] \n    | order(_createdAt desc)[0...10] {\n      _type, _id, _createdAt,\n      \"title\": coalesce(title, product->title),\n      description,\n      \"image\": coalesce(image.asset->url, product->mainImage.asset->url),\n      \"affiliateLink\": coalesce(affiliateLink, product->affiliateLink),\n      \"reviewSlug\": product->slug.current,\n      originalPrice, dealPrice, discountPercentage, category,\n      dealEndDate, isPrimeExclusive, couponCode, couponNote,\n      \"rating\": coalesce(rating, product->customerRating),\n      \"reviewCount\": coalesce(reviewCount, product->reviewCount)\n    }\n": FEATURED_DEALSResult;
    "\n  *[_type == \"deal\" && isActive == true && category == $category] \n    | order(_createdAt desc)[0...50] {\n      _type, _id, _createdAt,\n      \"title\": coalesce(title, product->title),\n      description,\n      \"image\": coalesce(image.asset->url, product->mainImage.asset->url),\n      \"affiliateLink\": coalesce(affiliateLink, product->affiliateLink),\n      \"reviewSlug\": product->slug.current,\n      originalPrice, dealPrice, discountPercentage,\n      dealEndDate, isPrimeExclusive, couponCode, couponNote,\n      \"rating\": coalesce(rating, product->customerRating),\n      \"reviewCount\": coalesce(reviewCount, product->reviewCount)\n    }\n": DEALS_BY_CATEGORYResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    _type,\n    title,\n    description,\n    \"logoMain\": logoMain.asset->url,\n    \"logoIcon\": logoIcon.asset->url,\n    \"logoBimi\": logoBimi.asset->url,\n    \"ogImage\": ogImage.asset->url,\n    socialLinks[] { platform, url },\n    contactEmail\n  }\n": SITE_SETTINGS_QUERYResult;
    "\n  *[_type == \"navigationMenu\"][0] {\n    _id,\n    title,\n    items[] {\n      _key,\n      title,\n      url,\n      children[] {\n        _key,\n        title,\n        url\n      }\n    }\n  }\n": NAVIGATION_MENUResult;
    "\n  *[_type == \"footerSettings\"][0] {\n    _id,\n    companyInfo,\n    links[] { title, url },\n    socialLinks[] { platform, url },\n    copyrightText\n  }\n": FOOTER_DATAResult;
    "{\n  \"heroPost\": coalesce(\n    *[_type in [\"topTenList\", \"article\"] && isFeaturedOnHome == true] | order(publishedAt desc) [0],\n    *[_type in [\"topTenList\", \"article\"]] | order(publishedAt desc) [0]\n  ) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    intro,\n    mainImage,\n    \"categorySlug\": coalesce(categories[0]->slug.current, category->slug.current)\n  },\n  \"sections\": *[_type == \"category\" && slug.current in $categories] | order(order asc, title asc) {\n    title,\n    \"slug\": slug.current,\n    description,\n    \"posts\": *[\n      (_type in [\"topTenList\", \"article\", \"tool\", \"product\"]) &&\n      (\n        ^._id in categories[]._ref ||\n        ^._id in displayCategories[]._ref ||\n        category._ref == ^._id ||\n        categories[0]._ref == ^._id\n      )\n    ] | order(publishedAt desc)[0...4] {\n      _id,\n      _type,\n      title,\n      \"slug\": slug.current,\n      publishedAt,\n      mainImage\n    }\n  },\n  \"upcomingPosts\": *[_type in [\"topTenList\", \"article\"] && category->slug.current == \"upcoming\"] | order(publishedAt desc)[0...4] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    mainImage\n  }\n}": HOME_QUERYResult;
    "\n  *[_type == \"category\" && slug.current == $slug][0]{\n    title, \n    description, \n    \"slug\": slug.current,\n    \"seo\": seo { metaTitle, metaDescription },\n    \"mainImage\": coalesce(\n      mainImage, \n      image,\n      *[references(^._id)][0].mainImage\n    ) { \"url\": asset->url, alt },\n    \"items\": *[\n      _type in [\"topTenList\", \"howTo\", \"tool\", \"holiday\", \"deal\", \"article\"] &&\n      (references(^._id) || category._ref == ^._id || categories[]._ref == ^._id)\n    ] | order(publishedAt desc)[0...100] { \n      _type, title, \"slug\": slug.current, publishedAt,\n      \"mainImage\": coalesce(mainImage, image, product->mainImage) { \"url\": asset->url, alt },\n      \"rawExcerpt\": coalesce(description, \"\", \"\")\n    }\n  }\n": CATEGORY_PAGE_QUERYResult;
    "\n  *[slug.current == $slug][0]{\n    _type,\n    \"slug\": slug.current, _id, title, description,\n    \"seoTitle\": coalesce(seo.metaTitle, title),\n    \"seoDescription\": \"\",\n    \"mainImage\": coalesce(mainImage, image, coverImage, product->mainImage) { \"url\": asset->url, alt },\n    \"category\": coalesce(categories[0], category)->{ \"title\": title, \"slug\": slug.current, \"menuLabel\": menuLabel },\n    \"publishedAt\": _createdAt, \"_updatedAt\": _updatedAt,\n    \"intro\": intro,\n    \"body\": body,\n    \"content\": content,\n    \"procedure\": procedure,\n    \"closingContent\": closingContent,\n    faqs[] { _key, question, answer },\n    startDate, endDate, locationName, address, ticketPrice\n  }\n": GENERIC_POST_QUERYResult;
    "{\n  \"featured\": *[_type == \"product\" && isFeaturedReview == true] | order(_updatedAt desc) [0...8] {\n    _id, title, \"rating\": customerRating, \"slug\": slug.current,\n    \"imageUrl\": coalesce(image.asset->url, mainImage.asset->url)\n  },\n  \"reviews\": *[_type == \"product\"] | order(_createdAt desc) [0...50] {\n    _id, title, \"rating\": customerRating, \"slug\": slug.current,\n    \"section\": reviewSection,\n    \"subCategoryTitle\": subCategory->menuLabel,\n    \"imageUrl\": coalesce(image.asset->url, mainImage.asset->url)\n  }\n}": REVIEWS_HUB_QUERYResult;
    "\n  *[_type == \"product\" && slug.current == $slug][0] {\n    _type,\n    _id,\n    title,\n    brand,\n    \"slug\": slug.current,\n    price,\n    currency,\n    availability,\n    priceTier,\n    retailer,\n    affiliateLink,\n    pros,\n    cons,\n    keyFeatures,\n    specifications[] { specLabel, specValue },\n    customerRating,\n    reviewCount,\n    verdict,\n    mainImage { \"url\": asset->url, alt },\n    itemDescription, \n    // SEO Data\n    \"seoTitle\": coalesce(seo.metaTitle, title),\n    \"seoDescription\": coalesce(seo.metaDescription, description, intro),\n    \"seoImage\": coalesce(seo.openGraphImage.asset->url, mainImage.asset->url),\n    \"category\": category->{title, \"slug\": slug.current}\n  }\n": PRODUCT_BY_SLUGResult;
    "\n  *[_type == \"product\"] | order(publishedAt desc)[0...100]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    brand,\n    price,\n    currency,\n    mainImage { \"url\": asset->url, alt },\n    customerRating,\n    reviewCount,\n    \"category\": category->title,\n    publishedAt\n  }\n": ALL_PRODUCTSResult;
    "\n  *[_type == \"product\" && category->slug.current == $categorySlug] \n    | order(publishedAt desc)[0...50]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      brand,\n      price,\n      currency,\n      mainImage { \"url\": asset->url, alt },\n      customerRating,\n      reviewCount,\n      publishedAt\n    }\n": PRODUCTS_BY_CATEGORYResult;
    "\n  *[_type == \"product\" && (title match $searchTerm || brand match $searchTerm)]\n    | order(publishedAt desc)[0...50]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      brand,\n      price,\n      currency,\n      mainImage { \"url\": asset->url, alt },\n      customerRating,\n      reviewCount\n    }\n": PRODUCT_SEARCHResult;
    "\n  *[_type == \"topTenList\" && slug.current == $slug][0] {\n    _type,\n    title,\n    \"slug\": slug.current,\n    publishedAt,\n    \"updatedAt\": _updatedAt, \n    \"seoTitle\": coalesce(seo.metaTitle, title),\n    \"seoDescription\": \"\",\n    mainImage { \"url\": asset->url, alt },\n    intro,\n    \"body\": body[],\n    closingContent,\n    showAffiliateDisclosure,\n    faqs[] { _key, question, answer },\n    listItems[] | order(rank asc) {\n      _key, rank, badgeLabel, whySelected, customVerdict,\n      product->{\n        _type, title,\n        \"slug\": slug.current,\n        priceTier, price, currency, availability, \n        affiliateLink, customerRating, verdict,\n        location, curriculum, feeRange, realityCheck, website,\n        \"rating\": coalesce(rating, customerRating),\n        entityType, code, country,\n        mainImage { \"url\": asset->url, alt },\n        heroFeature, keyFeatures[], pros[], cons[],\n        specifications[] { specLabel, specValue }\n      }\n    }\n  }\n": TOP_TEN_BY_SLUGResult;
    "\n  *[_type == \"topTenList\"] | order(publishedAt desc)[0...100]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    publishedAt,\n    mainImage { \"url\": asset->url, alt },\n    intro\n  }\n": ALL_TOP_TEN_LISTSResult;
    "\n  *[_type == \"topTenList\" && category->slug.current == $categorySlug]\n    | order(publishedAt desc)[0...50]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      publishedAt,\n      mainImage { \"url\": asset->url, alt },\n      intro\n    }\n": TOP_TEN_LISTS_BY_CATEGORYResult;
  }
}
